// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYhUXS-YUT7cMIKdHVpugnZUUmD2TxLM',
    appId: '1:1005978999262:web:e02562bc3e612d6a9ba54f',
    messagingSenderId: '1005978999262',
    projectId: 'aplikasi-gym',
    authDomain: 'aplikasi-gym.firebaseapp.com',
    storageBucket: 'aplikasi-gym.firebasestorage.app',
    measurementId: 'G-0RK4XSBNG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUOBkXYZm3oWMQZc7Bg2Mi_L6C3uFeyN4',
    appId: '1:1005978999262:android:638f950e9c1c00379ba54f',
    messagingSenderId: '1005978999262',
    projectId: 'aplikasi-gym',
    storageBucket: 'aplikasi-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSh-houaCibEX5sXJulq9pFpl3hNv1rc',
    appId: '1:1005978999262:ios:b4e83d3083144d369ba54f',
    messagingSenderId: '1005978999262',
    projectId: 'aplikasi-gym',
    storageBucket: 'aplikasi-gym.firebasestorage.app',
    iosBundleId: 'com.example.gymlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJSh-houaCibEX5sXJulq9pFpl3hNv1rc',
    appId: '1:1005978999262:ios:b4e83d3083144d369ba54f',
    messagingSenderId: '1005978999262',
    projectId: 'aplikasi-gym',
    storageBucket: 'aplikasi-gym.firebasestorage.app',
    iosBundleId: 'com.example.gymlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQYhUXS-YUT7cMIKdHVpugnZUUmD2TxLM',
    appId: '1:1005978999262:web:4692e042e82f8fe59ba54f',
    messagingSenderId: '1005978999262',
    projectId: 'aplikasi-gym',
    authDomain: 'aplikasi-gym.firebaseapp.com',
    storageBucket: 'aplikasi-gym.firebasestorage.app',
    measurementId: 'G-P4CY7S3PDK',
  );
}
